#!/usr/bin/env node

/**
 * Port Synchronization Script
 * Ensures all environment files use the same ports
 */

const fs = require('fs');
const path = require('path');

// Load port configuration
const portsConfig = require('./config/ports.json');

// Get environment (default to development)
const env = process.env.NODE_ENV || 'development';
const ports = portsConfig[env];

console.log('🔄 Synchronizing ports across the application...');
console.log(`📍 Environment: ${env}`);
console.log(`🚪 Ports configuration:`, ports);

// Update frontend .env.development
const frontendDevEnvPath = path.join(__dirname, 'frontend', '.env.development');
if (fs.existsSync(frontendDevEnvPath)) {
  let content = fs.readFileSync(frontendDevEnvPath, 'utf8');
  content = content.replace(
    /NEXT_PUBLIC_API_URL=.*/g,
    `NEXT_PUBLIC_API_URL=http://localhost:${ports.backend}`
  );
  content = content.replace(
    /NEXT_PUBLIC_WS_URL=.*/g,
    `NEXT_PUBLIC_WS_URL=ws://localhost:${ports.websocket}`
  );
  fs.writeFileSync(frontendDevEnvPath, content);
  console.log('✅ Updated frontend/.env.development');
}

// Update frontend .env.local if exists
const frontendLocalEnvPath = path.join(__dirname, 'frontend', '.env.local');
if (fs.existsSync(frontendLocalEnvPath)) {
  let content = fs.readFileSync(frontendLocalEnvPath, 'utf8');
  content = content.replace(
    /NEXT_PUBLIC_API_URL=.*/g,
    `NEXT_PUBLIC_API_URL=http://localhost:${ports.backend}`
  );
  content = content.replace(
    /NEXT_PUBLIC_WS_URL=.*/g,
    `NEXT_PUBLIC_WS_URL=ws://localhost:${ports.websocket}`
  );
  fs.writeFileSync(frontendLocalEnvPath, content);
  console.log('✅ Updated frontend/.env.local');
}

// Create/Update backend .env.development
const backendDevEnvPath = path.join(__dirname, 'backend', '.env.development');
const backendEnvContent = `# Auto-generated by sync-ports.js
NODE_ENV=${env}
PORT=${ports.backend}
WS_PORT=${ports.websocket}
FRONTEND_PORT=${ports.frontend}
FRONTEND_URL=http://localhost:${ports.frontend}
CVRP_PORT=${ports.cvrp}
CVRP_URL=http://localhost:${ports.cvrp}
`;

fs.writeFileSync(backendDevEnvPath, backendEnvContent);
console.log('✅ Created/Updated backend/.env.development');

// Update package.json scripts to use dynamic ports
const packageJsonPath = path.join(__dirname, 'package.json');
if (fs.existsSync(packageJsonPath)) {
  const packageJson = require(packageJsonPath);

  // Update dev scripts with dynamic ports
  packageJson.scripts['dev:backend'] = `cd backend && PORT=${ports.backend} node src/app.js`;
  packageJson.scripts['dev:websocket'] = `cd backend && WS_PORT=${ports.websocket} node src/demo/websocket-server.js`;
  packageJson.scripts['dev:frontend'] = `cd frontend && NEXT_PUBLIC_API_URL=http://localhost:${ports.backend} NEXT_PUBLIC_WS_URL=ws://localhost:${ports.websocket} npm run dev -- -p ${ports.frontend}`;

  fs.writeFileSync(packageJsonPath, JSON.stringify(packageJson, null, 2));
  console.log('✅ Updated package.json scripts');
}

console.log('\n✨ Port synchronization complete!');
console.log('\n📋 Configuration Summary:');
console.log(`   Backend API: http://localhost:${ports.backend}`);
console.log(`   Frontend UI: http://localhost:${ports.frontend}`);
console.log(`   WebSocket: ws://localhost:${ports.websocket}`);
console.log(`   Analytics: http://localhost:${ports.analytics}`);
console.log(`   CVRP Service: http://localhost:${ports.cvrp}`);
console.log('\n🚀 Run "npm run dev" to start with synchronized ports');