# Production Deployment Configuration for BARQ/BULLET Fleet Management System
# Google Cloud Platform - App Engine Configuration

runtime: nodejs18
env: standard

# Instance configuration for production load
instance_class: F4
automatic_scaling:
  min_instances: 3
  max_instances: 50
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.7
  max_concurrent_requests: 100
  min_pending_latency: 30ms
  max_pending_latency: automatic

# Environment variables
env_variables:
  NODE_ENV: "production"
  SERVICE_NAME: "barq-bullet-fleet-management"

  # Service Types Configuration
  BARQ_ENABLED: "true"
  BARQ_MAX_RADIUS: "5"
  BARQ_MAX_TIME: "60"
  BULLET_ENABLED: "true"
  BULLET_MAX_RADIUS: "30"
  BULLET_MAX_TIME: "240"

  # Agent Configuration
  AGENTS_ENABLED: "true"
  CONTINUOUS_MONITORING: "true"
  AGENT_HEALTH_CHECK_INTERVAL: "60000"

  # Performance Thresholds
  SLA_COMPLIANCE_TARGET: "0.95"
  MAX_RESPONSE_TIME: "1000"
  MAX_OPTIMIZATION_TIME: "5000"

  # Database Configuration
  DB_CONNECTION_LIMIT: "20"
  DB_IDLE_TIMEOUT: "30000"

  # Caching
  REDIS_ENABLED: "true"
  CACHE_TTL: "300"

  # Monitoring
  ENABLE_METRICS: "true"
  ENABLE_TRACING: "true"
  ENABLE_PROFILING: "true"

# VPC connector for private resources
vpc_access_connector:
  name: projects/PROJECT_ID/locations/REGION/connectors/fleet-connector

# Health checks
readiness_check:
  path: "/health/ready"
  check_interval_sec: 10
  timeout_sec: 5
  failure_threshold: 3
  success_threshold: 2
  app_start_timeout_sec: 300

liveness_check:
  path: "/health/live"
  check_interval_sec: 30
  timeout_sec: 10
  failure_threshold: 3
  success_threshold: 1
  initial_delay_sec: 30

# Handlers for different services
handlers:
  # API endpoints
  - url: /api/.*
    script: auto
    secure: always
    redirect_http_response_code: 301

  # WebSocket endpoint for real-time updates
  - url: /ws/.*
    script: auto
    secure: always

  # Health check endpoints
  - url: /health/.*
    script: auto
    secure: always

  # Static files
  - url: /static
    static_dir: static
    secure: always
    http_headers:
      X-Content-Type-Options: nosniff
      X-Frame-Options: DENY
      X-XSS-Protection: 1; mode=block

  # Documentation
  - url: /docs
    static_dir: docs
    secure: always

  # Default handler
  - url: /.*
    script: auto
    secure: always

# Inbound services
inbound_services:
  - warmup

# Resources allocation
resources:
  cpu: 4
  memory_gb: 8
  disk_size_gb: 20

# Network configuration
network:
  forwarded_ports:
    - 8080
    - 8443
  session_affinity: true

# Error handlers
error_handlers:
  - file: errors/404.html
    error_code: 404
  - file: errors/500.html
    error_code: 500
  - file: errors/503.html
    error_code: 503

# Service account
service_account: fleet-management@PROJECT_ID.iam.gserviceaccount.com